# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Pod Install
        if: steps.cache-cocoapods.outputs.cache-hit != 'true'
        run: pod install

      - name: Select Xcode version # Xcode 11.2 を使う
        run: sudo xcode-select -s '/Applications/Xcode_11.2.app/Contents/Developer'

      - name: Show Xcode version
        run: xcodebuild -version
        
      - name: Build # シミュレーター向けにビルド
        run: xcodebuild -workspace GitActionsEx.xcworkspace -scheme GitActionsEx -sdk iphonesimulator -configuration Debug build

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
